apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: gobg
    patch: |-
      - op: add
        path: /spec/type
        value: LoadBalancer
