name: Docker Image CI

on:
  push:
    branches: [ dev ]
jobs:
  generatePR:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Variables
        id: vars
        run: |
          echo ::set-output name=image_tag::$(echo $GITHUB_SHA  | cut -c1-6)
      - name: Create Pull Request
        run: |
          gh pr create --title "Update ${{ steps.vars.outputs.image_tag }}" --body "This updates the color of the box for commit ${{ steps.vars.outputs.image_tag }}" --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##
##