name: Docker Image CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: gobg
      - name: Set Variables
        id: vars
        run: |
          cd ${GITHUB_WORKSPACE}/gobg
          echo ::set-output name=image_tag::$(echo $GITHUB_SHA  | cut -c1-6)
          cd ${GITHUB_WORKSPACE}/gobg
          echo ::set-output name=commit_msg::$(git log -1 --pretty="%s")
          cd -
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push the Docker image
        env:
          CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/gobg:${{ steps.vars.outputs.image_tag }}
        run: |
          cd ${GITHUB_WORKSPACE}/gobg
          docker build . --file Containerfile --tag $CF_IMAGE && docker push $CF_IMAGE
          echo "Image should be accessible to your local machine (after docker login) by:"
          echo "docker pull $CF_IMAGE"
          docker pull $CF_IMAGE
          cd -
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DEPLOY_REPOSITORY }}
          token: ${{ secrets.CF_GITHUB_TOKEN }}
          ref: main
          path: gobg-deploy
      - name: Set image on the rollout config
        uses: mikefarah/yq@master
        with:
          cmd: yq '.spec.template.spec.containers.[0].image |= "${{ secrets.DOCKERHUB_USERNAME }}/gobg:${{ steps.vars.outputs.image_tag }}"' ${GITHUB_WORKSPACE}/gobg-deploy/deploy/overlays/rollouts/rollout.yaml
      - name: Commit changes
        run: |
          cd $GITHUB_WORKSPACE/gobg-deploy/
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "noreply@github.com"
          git add .
          git commit -am "Update Image to ${{ steps.vars.outputs.image_tag }} for ${{ steps.vars.outputs.commit_msg }}"
          git push origin main
      ###- name: Create Pull Request
        ###run: gh pr create --title "Update Image in Prod to ${{ steps.vars.outputs.image_tag }}" --body "Update Image to ${{ steps.vars.outputs.image_tag }} for ${{ steps.vars.outputs.commit_msg }}" --base main 
        ###env:
          ###GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify Codefresh Platfrom
        uses: codefresh-io/codefresh-report-image@latest
        with:
          CF_RUNTIME_NAME: 'codefresh-hosted'
          CF_API_KEY: ${{ secrets.USER_TOKEN }}
          CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/gobg:${{ steps.vars.outputs.image_tag }}
          CF_CONTAINER_REGISTRY_INTEGRATION: "dockerhub"
          CF_GITHUB_TOKEN: ${{ secrets.CF_GITHUB_TOKEN }}    
          CF_GIT_BRANCH: ${{ github.ref_name }}
          CF_JIRA_INTEGRATION: "jira" 
          CF_JIRA_PROJECT_PREFIX: "SA"
          CF_JIRA_MESSAGE: "Update for SA-498"

          #CF_ENRICHERS: "jira, git"
##
##